name: Create Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Set variables
        run: |
          PATCH=$(cat version.txt)
          MINOR=$(echo $PATCH | cut -d '.' -f 1,2)
          MAJOR=$(echo $PATCH | cut -d '.' -f 1)
          echo "IOTFSDB_PATCH=$PATCH" >> $GITHUB_ENV
          echo "IOTFSDB_MINOR=$MINOR" >> $GITHUB_ENV
          echo "IOTFSDB_MAJOR=$MAJOR" >> $GITHUB_ENV
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 23
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Copy Jar for Docker
        run: cp ./build/libs/*.jar ./docker/iotfsdb.jar
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Build and Push
        id: docker
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: true
          tags: |
            jhuebert/iotfsdb:${{ env.IOTFSDB_PATCH }}
            jhuebert/iotfsdb:${{ env.IOTFSDB_MINOR }}
            jhuebert/iotfsdb:${{ env.IOTFSDB_MAJOR }}
          pull: true
          no-cache: true
          provenance: true
          sbom: true
          platforms: linux/amd64, linux/arm64
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/libs/iotfsdb-*.jar
          fail_on_unmatched_files: true
          generate_release_notes: true
          name: ${{ env.IOTFSDB_PATCH }}
          tag_name: ${{ env.IOTFSDB_PATCH }}
