name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "1.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Copy Jar for Docker
        run: cp ./build/libs/*.jar ./docker/iotfsdb.jar
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Build and Push
        id: docker
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: true
          tags: |
            jhuebert/iotfsdb:1
            jhuebert/iotfsdb:${{ github.ref_name }}
          pull: true
          no-cache: true
          provenance: true
          sbom: true
          platforms: linux/amd64, linux/arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/libs/iotfsdb-*.jar
          fail_on_unmatched_files: true
